services:
  postgres:
    image: postgres:16-alpine
    container_name: ghost_ai_postgres
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
    environment:
      POSTGRES_USER: westtdev
      POSTGRES_PASSWORD: estratico
      POSTGRES_DB: ghost_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: